apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
namePrefix: raven-

bases:
- ../rbac
- ../agent

secretGenerator:
  - envs:
      - psk.env
    name: agent-secret
    type: Opaque